package com.mitch.dimlight.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF1E5ABE)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD9E2FF)
val LightOnPrimaryContainer = Color(0xFF001944)
val LightSecondary = Color(0xFF575E71)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDCE2F9)
val LightOnSecondaryContainer = Color(0xFF141B2C)
val LightTertiary = Color(0xFF725572)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFDD7FA)
val LightOnTertiaryContainer = Color(0xFF2A132C)
val LightError = Color(0xFFBA1A1A)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnError = Color(0xFFFFFFFF)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFEFBFF)
val LightOnBackground = Color(0xFF1B1B1F)
val LightSurface = Color(0xFFFEFBFF)
val LightOnSurface = Color(0xFF1B1B1F)
val LightSurfaceVariant = Color(0xFFE1E2EC)
val LightOnSurfaceVariant = Color(0xFF44464F)
val LightOutline = Color(0xFF757780)
val LightInverseOnSurface = Color(0xFFF2F0F4)
val LightInverseSurface = Color(0xFF303034)
val LightInversePrimary = Color(0xFFB0C6FF)
val LightSurfaceTint = Color(0xFF1E5ABE)
val LightOutlineVariant = Color(0xFFC5C6D0)
val LightScrim = Color(0xFF000000)

val DarkPrimary = Color(0xFFB0C6FF)
val DarkOnPrimary = Color(0xFF002D6E)
val DarkPrimaryContainer = Color(0xFF00429A)
val DarkOnPrimaryContainer = Color(0xFFD9E2FF)
val DarkSecondary = Color(0xFFBFC6DC)
val DarkOnSecondary = Color(0xFF293042)
val DarkSecondaryContainer = Color(0xFF404659)
val DarkOnSecondaryContainer = Color(0xFFDCE2F9)
val DarkTertiary = Color(0xFFDFBBDE)
val DarkOnTertiary = Color(0xFF412742)
val DarkTertiaryContainer = Color(0xFF593D5A)
val DarkOnTertiaryContainer = Color(0xFFFDD7FA)
val DarkError = Color(0xFFFFB4AB)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnError = Color(0xFF690005)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1B1B1F)
val DarkOnBackground = Color(0xFFE3E2E6)
val DarkSurface = Color(0xFF1B1B1F)
val DarkOnSurface = Color(0xFFE3E2E6)
val DarkSurfaceVariant = Color(0xFF44464F)
val DarkOnSurfaceVariant = Color(0xFFC5C6D0)
val DarkOutline = Color(0xFF8F9099)
val DarkInverseOnSurface = Color(0xFF1B1B1F)
val DarkInverseSurface = Color(0xFFE3E2E6)
val DarkInversePrimary = Color(0xFF1E5ABE)
val DarkSurfaceTint = Color(0xFFB0C6FF)
val DarkOutlineVariant = Color(0xFF44464F)
val DarkScrim = Color(0xFF000000)

val Seed = Color(0xFF004DB1)
